name: Build and push base images
on:
  push:
    branches:
      - main
  schedule:
    # For å få med oss nye versjoner av navikt/java så bygger vi ukentlig ny versjon (hvis det ikke har skjedd endringer så blir dette en NO-OP for konsumenter av imaget)
    - cron: '0 12 * * 3' # Kjør onsdag kl 12:00 hver uke

env:
  IMAGE_JAVA: ghcr.io/${{ github.repository }}/java

jobs:
  build-and-push-java:
    name: Build and push java base images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build and push base images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${GITHUB_REPOSITORY} --password-stdin
          docker build -t ${IMAGE_JAVA}:11 --build-arg java_version=11 java
          docker build -t ${IMAGE_JAVA}:15 --build-arg java_version=15 java
          docker build -t ${IMAGE_JAVA}:17 --build-arg java_version=17 java
          docker push ${IMAGE_JAVA}:11
          docker push ${IMAGE_JAVA}:15
          docker push ${IMAGE_JAVA}:17